/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["AppController_getHello"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["AppController_health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["AppController_readiness"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/metrics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["MetricsController_getMetrics"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["AuthController_register"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["AuthController_login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/demo": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["AuthController_demo"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["AuthController_logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["UsersController_getCurrentUser"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/check-username/{username}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["UsersController_checkUsername"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["UsersController_searchUsers"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/{username}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["UsersController_getUserProfile"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/profile": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["UsersController_updateProfile"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/posts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["PostsController_createPost"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/posts/feed": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["PostsController_getFeed"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/posts/user/{username}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["PostsController_getUserPosts"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/posts/explore": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["PostsController_getExplore"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/posts/{postId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["PostsController_getPost"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/posts/{postId}/like": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["PostsController_likePost"];
    delete: operations["PostsController_unlikePost"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/posts/{postId}/comments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["PostsController_getComments"];
    put?: never;
    post: operations["PostsController_createComment"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/posts/{postId}/comments/{commentId}/like": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["PostsController_likeComment"];
    delete: operations["PostsController_unlikeComment"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/follows/{username}/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["FollowsController_getFollowStatus"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/follows/{username}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["FollowsController_followUser"];
    delete: operations["FollowsController_unfollowUser"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/notifications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["NotificationsController_getNotifications"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/media/presign": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["MediaController_createUploadUrl"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ai/rewrite": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["AiController_rewrite"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    RegisterDto: {
      /** Format: email */
      email: string;
      username: string;
      fullName: string;
      password: string;
    };
    PrivateUserProfileDto: {
      id: string;
      username: string;
      fullName: string;
      profilePictureUrl?: string;
      bio?: string;
      postCount: number;
      followerCount: number;
      followingCount: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      email: string;
    };
    AuthRegisterResponseDto: {
      message: string;
      user: components["schemas"]["PrivateUserProfileDto"];
    };
    LoginDto: {
      /** Format: email */
      email: string;
      password: string;
    };
    AuthLoginResponseDto: {
      message: string;
      user: components["schemas"]["PrivateUserProfileDto"];
      accessToken: string;
      isDemoUser?: boolean;
      /** Format: date-time */
      demoExpiresAt?: string;
    };
    AuthLogoutResponseDto: {
      message: string;
    };
    UserSearchItemDto: {
      /** @example b6cf7a42-3f7a-4a7b-97a2-6c8a13d7b56e */
      id: string;
      /** @example ava */
      username: string;
      /** @example Ava Thompson */
      fullName: string;
      /** @example https://cdn.isntgram.ai/avatars/ava.jpg */
      profilePictureUrl?: string;
    };
    UserSearchResponseDto: {
      items: components["schemas"]["UserSearchItemDto"][];
    };
    PublicUserProfileDto: {
      id: string;
      username: string;
      fullName: string;
      profilePictureUrl?: string;
      bio?: string;
      postCount: number;
      followerCount: number;
      followingCount: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    UpdateProfileDto: {
      fullName: string;
      username: string;
    };
    PostAuthorDto: {
      /** @example b6cf7a42-3f7a-4a7b-97a2-6c8a13d7b56e */
      id: string;
      /** @example ava */
      username: string;
      /** @example Ava Thompson */
      fullName: string;
      /** @example https://cdn.isntgram.ai/avatars/ava.jpg */
      profilePictureUrl?: string;
    };
    CommentDto: {
      /** @example 66efb64c-702f-46f5-9b44-7c9f2b0a0d61 */
      id: string;
      /** @example 7c1a2f04-1cf3-4c75-b42f-8f6c0f3e4d5a */
      postId: string;
      /** @example Great point — I ran into the same thing last week. */
      content: string;
      /** @example 12 */
      likeCount: number;
      /**
       * @description Whether the authenticated viewer has liked this comment.
       * @example false
       */
      likedByViewer: boolean;
      /**
       * Format: date-time
       * @example 2025-12-19T10:12:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @example 2025-12-19T10:12:00.000Z
       */
      updatedAt: string;
      author: components["schemas"]["PostAuthorDto"];
    };
    PostDto: {
      /** @example 7c1a2f04-1cf3-4c75-b42f-8f6c0f3e4d5a */
      id: string;
      /** @example Shipping a fresh batch of ideas after today's research sprint. */
      content: string;
      /** @example https://cdn.isntgram.ai/uploads/ava/post-cover.jpg */
      mediaUrl?: string;
      /** @example 0 */
      likeCount: number;
      /** @example 0 */
      commentCount: number;
      /** @description Preview comments (up to 3) for feed/profile rendering without extra round-trips. */
      previewComments: components["schemas"]["CommentDto"][];
      /**
       * @description Whether the current viewer has liked this post (false for anonymous viewers)
       * @example false
       */
      likedByViewer: boolean;
      /**
       * Format: date-time
       * @example 2025-12-19T10:12:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @example 2025-12-19T10:12:00.000Z
       */
      updatedAt: string;
      author: components["schemas"]["PostAuthorDto"];
    };
    FeedResponseDto: {
      /**
       * @example [
       *       {
       *         "id": "7c1a2f04-1cf3-4c75-b42f-8f6c0f3e4d5a",
       *         "content": "Shipping a fresh batch of ideas after today's research sprint.",
       *         "mediaUrl": "https://cdn.isntgram.ai/uploads/ava/post-cover.jpg",
       *         "createdAt": "2025-12-19T10:12:00.000Z",
       *         "updatedAt": "2025-12-19T10:12:00.000Z",
       *         "author": {
       *           "id": "b6cf7a42-3f7a-4a7b-97a2-6c8a13d7b56e",
       *           "username": "ava",
       *           "fullName": "Ava Thompson",
       *           "profilePictureUrl": "https://cdn.isntgram.ai/avatars/ava.jpg"
       *         }
       *       }
       *     ]
       */
      items: components["schemas"]["PostDto"][];
      /**
       * @description Use as cursor for next page
       * @example MjAyNS0xMi0xOVQxMDoxMjowMC4wMDBafDdjMWEyZjA0LTFjZjMtNGM3NS1iNDJmLThmNmMwZjNlNGQ1YQ==
       */
      nextCursor?: string;
    };
    PostLikeStatusDto: {
      /** @example true */
      isLiked: boolean;
      /** @example 12 */
      likeCount: number;
    };
    CommentLikeStatusDto: {
      /** @example true */
      isLiked: boolean;
      /** @example 12 */
      likeCount: number;
    };
    CommentsResponseDto: {
      items: components["schemas"]["CommentDto"][];
      /**
       * @description Opaque cursor from previous page
       * @example MjAyNS0xMi0xOVQxMDoxMjowMC4wMDBafDY2ZWZiNjRjLTcwMmYtNDZmNS05YjQ0LTdjOWYyYjBhMGQ2MQ==
       */
      nextCursor?: string;
    };
    ApiErrorDto: {
      /** @example 400 */
      statusCode: number;
      /** @example 2025-12-19T12:34:56.789Z */
      timestamp: string;
      /** @example /api/posts/feed?limit=20 */
      path: string;
      /** @example req_9a6b3f0c-4a0a-4f11-9c61-2f6a3c5d1b2c */
      requestId?: string;
      /** @example Invalid cursor */
      message: string;
      /**
       * @example [
       *       "username must be longer than or equal to 3 characters"
       *     ]
       */
      errors?: string[];
      /** @example BadRequestException */
      error: string;
    };
    CreatePostDto: {
      /** @example Shipping a fresh batch of ideas after today's research sprint. */
      content: string;
      /**
       * Format: uri
       * @example https://cdn.isntgram.ai/uploads/ava/post-cover.jpg
       */
      mediaUrl?: string;
    };
    CreateCommentDto: {
      content: string;
    };
    FollowStatusDto: {
      /** @example true */
      isFollowing: boolean;
    };
    NotificationActorDto: {
      /** @example b6cf7a42-3f7a-4a7b-97a2-6c8a13d7b56e */
      id: string;
      /** @example ava */
      username: string;
      /** @example Ava Thompson */
      fullName: string;
      /** @example https://cdn.isntgram.ai/avatars/ava.jpg */
      profilePictureUrl?: string;
    };
    NotificationDto: {
      /** @example 66efb64c-702f-46f5-9b44-7c9f2b0a0d61 */
      id: string;
      /**
       * @example like
       * @enum {string}
       */
      type: "follow" | "like" | "comment";
      /**
       * Format: date-time
       * @example 2025-12-19T10:12:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @example 2025-12-19T10:12:00.000Z
       */
      readAt?: string;
      actor: components["schemas"]["NotificationActorDto"];
      /**
       * @description Associated post id (for like/comment notifications).
       * @example 7c1a2f04-1cf3-4c75-b42f-8f6c0f3e4d5a
       */
      postId?: string;
      /**
       * @description Associated post media url (for like/comment notifications).
       * @example https://cdn.isntgram.ai/uploads/ava/post-cover.jpg
       */
      postMediaUrl?: string;
      /**
       * @description Associated comment id (for comment notifications).
       * @example 66efb64c-702f-46f5-9b44-7c9f2b0a0d61
       */
      commentId?: string;
    };
    NotificationsResponseDto: {
      items: components["schemas"]["NotificationDto"][];
      /**
       * @description Opaque cursor for pagination
       * @example MjAyNS0xMi0xOVQxMDoxMjowMC4wMDBafDY2ZWZiNjRjLTcwMmYtNDZmNS05YjQ0LTdjOWYyYjBhMGQ2MQ==
       */
      nextCursor?: string;
    };
    UploadUrlDto: {
      /** @example https://s3.us-east-1.amazonaws.com/isntgram-media/uploads/ava/1702990000-uuid-photo.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=... */
      uploadUrl: string;
      /** @example https://cdn.isntgram.ai/uploads/ava/1702990000-uuid-photo.jpg */
      publicUrl: string;
      /** @example uploads/ava/1702990000-uuid-photo.jpg */
      key: string;
      /** @example 900 */
      expiresIn: number;
    };
    CreateUploadUrlDto: {
      /** @example photo.jpg */
      fileName: string;
      /** @example image/jpeg */
      contentType: string;
      /**
       * @description File size in bytes
       * @example 245000
       */
      contentLength: number;
    };
    AiRewriteResponseDto: {
      /** @example Shipping a fresh batch of ideas after today's research sprint — distilled and ready to share. */
      content: string;
      /** @enum {string} */
      provider: "mock" | "openai";
      /** @example gpt-4o-mini */
      model?: string;
    };
    AiRewriteRequestDto: {
      /** @example Shipping a fresh batch of ideas after today's research sprint. */
      content: string;
      /**
       * @default professional
       * @enum {string}
       */
      tone?: "professional" | "friendly" | "concise";
      /**
       * @description Maximum character length for the rewritten content
       * @default 2000
       */
      maxLength?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AppController_getHello: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AppController_health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AppController_readiness: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MetricsController_getMetrics: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Prometheus metrics exposition */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthRegisterResponseDto"];
        };
      };
    };
  };
  AuthController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthLoginResponseDto"];
        };
      };
    };
  };
  AuthController_demo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthLoginResponseDto"];
        };
      };
    };
  };
  AuthController_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthLogoutResponseDto"];
        };
      };
    };
  };
  UsersController_getCurrentUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PrivateUserProfileDto"];
        };
      };
    };
  };
  UsersController_checkUsername: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        username: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  UsersController_searchUsers: {
    parameters: {
      query: {
        /** @description Search term (username or name). */
        q: string;
        /** @description Maximum number of results. */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserSearchResponseDto"];
        };
      };
    };
  };
  UsersController_getUserProfile: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        username: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublicUserProfileDto"];
        };
      };
    };
  };
  UsersController_updateProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProfileDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PrivateUserProfileDto"];
        };
      };
    };
  };
  PostsController_createPost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePostDto"];
      };
    };
    responses: {
      /** @description Post created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PostDto"];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
      /** @description Missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
    };
  };
  PostsController_getFeed: {
    parameters: {
      query?: {
        /** @description Opaque cursor from previous page */
        cursor?: string;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Feed results */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeedResponseDto"];
        };
      };
      /** @description Invalid cursor */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
      /** @description Missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
    };
  };
  PostsController_getUserPosts: {
    parameters: {
      query?: {
        /** @description Opaque cursor from previous page */
        cursor?: string;
        limit?: number;
      };
      header?: never;
      path: {
        username: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User posts */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeedResponseDto"];
        };
      };
      /** @description Invalid cursor */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
    };
  };
  PostsController_getExplore: {
    parameters: {
      query?: {
        /** @description Opaque cursor from previous page */
        cursor?: string;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Explore results */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeedResponseDto"];
        };
      };
      /** @description Invalid cursor */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
      /** @description Missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
    };
  };
  PostsController_getPost: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        postId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Post details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PostDto"];
        };
      };
      /** @description Post not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
    };
  };
  PostsController_likePost: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        postId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Liked post */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PostLikeStatusDto"];
        };
      };
      /** @description Missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
      /** @description Post not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
    };
  };
  PostsController_unlikePost: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        postId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Unliked post */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PostLikeStatusDto"];
        };
      };
      /** @description Missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
      /** @description Post not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
    };
  };
  PostsController_getComments: {
    parameters: {
      query?: {
        /** @description Opaque cursor from previous page */
        cursor?: string;
        limit?: number;
      };
      header?: never;
      path: {
        postId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Comment list */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommentsResponseDto"];
        };
      };
      /** @description Invalid cursor */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
      /** @description Post not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
    };
  };
  PostsController_createComment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        postId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCommentDto"];
      };
    };
    responses: {
      /** @description Comment created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommentDto"];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
      /** @description Missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
      /** @description Post not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
    };
  };
  PostsController_likeComment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        postId: string;
        commentId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Liked comment */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommentLikeStatusDto"];
        };
      };
      /** @description Missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
      /** @description Post or comment not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
    };
  };
  PostsController_unlikeComment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        postId: string;
        commentId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Unliked comment */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommentLikeStatusDto"];
        };
      };
      /** @description Missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
      /** @description Post or comment not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
    };
  };
  FollowsController_getFollowStatus: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        username: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Follow status */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FollowStatusDto"];
        };
      };
      /** @description Missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
    };
  };
  FollowsController_followUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        username: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Followed user */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FollowStatusDto"];
        };
      };
      /** @description Cannot follow yourself */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
      /** @description Missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
    };
  };
  FollowsController_unfollowUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        username: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Unfollowed user */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FollowStatusDto"];
        };
      };
      /** @description Missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
    };
  };
  NotificationsController_getNotifications: {
    parameters: {
      query?: {
        /** @description Opaque cursor from previous page */
        cursor?: string;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Notifications list */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NotificationsResponseDto"];
        };
      };
      /** @description Invalid cursor */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
      /** @description Missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
    };
  };
  MediaController_createUploadUrl: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUploadUrlDto"];
      };
    };
    responses: {
      /** @description Presigned upload URL */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UploadUrlDto"];
        };
      };
      /** @description Unsupported media type */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
      /** @description Missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
      /** @description Media storage is not configured */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
    };
  };
  AiController_rewrite: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AiRewriteRequestDto"];
      };
    };
    responses: {
      /** @description Rewrite post content using an AI provider */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AiRewriteResponseDto"];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
      /** @description Missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorDto"];
        };
      };
    };
  };
}
