version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: isntgram-postgres
    environment:
      POSTGRES_DB: isntgram
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d isntgram"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
