import { Module, MiddlewareConsumer, NestModule } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ThrottlerModule } from '@nestjs/throttler';
import { APP_FILTER, APP_GUARD, APP_INTERCEPTOR } from '@nestjs/core';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { AuthModule } from './auth/auth.module';
import { UsersModule } from './users/users.module';
import { PostsModule } from './posts/posts.module';
import { FollowsModule } from './follows/follows.module';
import { MediaModule } from './media/media.module';
import { AiModule } from './ai/ai.module';
import { MetricsModule } from './metrics/metrics.module';
import { NotificationsModule } from './notifications/notifications.module';
import { GlobalExceptionFilter } from './common/filters/global-exception.filter';
import { join } from 'path';
import { RequestIdMiddleware } from './common/middleware/request-id.middleware';
import { MetricsInterceptor } from './metrics/metrics.interceptor';
import { HttpLoggingInterceptor } from './common/interceptors/http-logging.interceptor';
import { validateEnv } from './config/env.validation';
import { getPostgresSslOptions } from './config/postgres-ssl';
import { UserThrottlerGuard } from './common/guards/user-throttler.guard';

function getDatabaseModules() {
  if (process.env.SKIP_DB === 'true') {
    return [];
  }

  return [
    TypeOrmModule.forRootAsync({
      imports: [ConfigModule],
      useFactory: () => {
        // Use SQLite for tests (including CI E2E), PostgreSQL for other environments.
        // Important: this factory runs after ConfigModule loads `.env.local`/`.env`,
        // so `process.env` includes values generated by scripts/dev-db.sh.
        const nodeEnv = process.env.NODE_ENV ?? 'development';
        const isTestEnv = nodeEnv === 'test';
        const baseConfig = {
          autoLoadEntities: true,
          migrations: [join(__dirname, 'migrations', '*{.ts,.js}')],
        };

        if (isTestEnv) {
          return {
            type: 'sqlite' as const,
            database: ':memory:',
            synchronize: true,
            logging: false,
            ...baseConfig,
          };
        }

        return {
          type: 'postgres' as const,
          url:
            process.env.DATABASE_URL ||
            'postgresql://postgres:password@localhost:5432/isntgram',
          synchronize: false,
          // Safe default: never run migrations automatically in production.
          // In production, run migrations as an explicit deploy step.
          migrationsRun: nodeEnv !== 'production',
          logging: nodeEnv === 'development',
          ssl: getPostgresSslOptions(process.env),
          ...baseConfig,
        };
      },
    }),
  ];
}

function getFeatureModules() {
  if (process.env.SKIP_DB === 'true') {
    return [];
  }
  return [
    AuthModule,
    UsersModule,
    PostsModule,
    FollowsModule,
    NotificationsModule,
    MediaModule,
    AiModule,
  ];
}

function getThrottlerOptions() {
  const ttl = Number(process.env.THROTTLER_TTL ?? 60000);
  const defaultLimit = process.env.NODE_ENV === 'test' ? 10000 : 10;
  const limit = Number(process.env.THROTTLER_LIMIT ?? defaultLimit);

  return [
    {
      ttl: Number.isFinite(ttl) ? ttl : 60000,
      limit: Number.isFinite(limit) ? limit : defaultLimit,
    },
  ];
}

@Module({
  imports: [
    ConfigModule.forRoot({
      isGlobal: true,
      envFilePath: ['.env.local', '.env'],
      validate: validateEnv,
    }),
    ThrottlerModule.forRoot(getThrottlerOptions()),
    MetricsModule,
    ...getDatabaseModules(),
    ...getFeatureModules(),
  ],
  controllers: [AppController],
  providers: [
    AppService,
    {
      provide: APP_GUARD,
      useClass: UserThrottlerGuard,
    },
    {
      provide: APP_FILTER,
      useClass: GlobalExceptionFilter,
    },
    RequestIdMiddleware,
    {
      provide: APP_INTERCEPTOR,
      useClass: MetricsInterceptor,
    },
    {
      provide: APP_INTERCEPTOR,
      useClass: HttpLoggingInterceptor,
    },
  ],
})
export class AppModule implements NestModule {
  configure(consumer: MiddlewareConsumer) {
    consumer.apply(RequestIdMiddleware).forRoutes('*');
  }
}
