#!/bin/bash

# Start PostgreSQL and MinIO for local development (supports docker compose v1 and v2)
set -e

echo "Starting development infrastructure..."

# Prefer a stable default, but fall back if the port is already taken (common when multiple projects use Postgres).
DEFAULT_POSTGRES_PORT="${POSTGRES_PORT:-5432}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-password}"
export POSTGRES_PASSWORD

port_is_open() {
  local port="$1"
  if command -v nc >/dev/null 2>&1; then
    nc -z 127.0.0.1 "${port}" >/dev/null 2>&1
    return $?
  fi
  if command -v lsof >/dev/null 2>&1; then
    lsof -nP -iTCP:"${port}" -sTCP:LISTEN >/dev/null 2>&1
    return $?
  fi
  return 1
}

pick_postgres_port() {
  local desired="$1"
  local candidates=("${desired}" 5433 5434 5435 5436)
  for candidate in "${candidates[@]}"; do
    if port_is_open "${candidate}"; then
      continue
    fi
    echo "${candidate}"
    return 0
  done
  return 1
}

POSTGRES_PORT="$(pick_postgres_port "${DEFAULT_POSTGRES_PORT}")"
export POSTGRES_PORT

if [[ "${POSTGRES_PORT}" != "${DEFAULT_POSTGRES_PORT}" ]]; then
  echo "⚠️  Port ${DEFAULT_POSTGRES_PORT} is in use; using Postgres port ${POSTGRES_PORT} for Isntgram."
fi

# Check if Docker is running
if ! docker info > /dev/null 2>&1; then
  echo "Error: Docker is not running. Please start Docker Desktop and try again."
  exit 1
fi

# Detect compose command
if command -v docker-compose >/dev/null 2>&1; then
  COMPOSE_CMD="docker-compose"
elif docker compose version >/dev/null 2>&1; then
  COMPOSE_CMD="docker compose"
else
  echo "Error: Neither docker-compose nor 'docker compose' is available."
  echo "- On macOS, install Docker Desktop: https://docs.docker.com/desktop/install/mac-install/"
  echo "- Or install docker-compose plugin: brew install docker-compose"
  exit 1
fi

# Start infrastructure services
$COMPOSE_CMD up -d postgres minio minio-init

# Wait for database to be ready
echo "Waiting for PostgreSQL to be ready..."
until $COMPOSE_CMD exec -T postgres pg_isready -U postgres -d isntgram >/dev/null 2>&1; do
  echo "PostgreSQL is not ready yet. Waiting..."
  sleep 2
done

# Ensure the port is actually published to the host (avoids confusing scenarios when another container already binds 5432).
PUBLISHED_POSTGRES_PORT="$(
  $COMPOSE_CMD port postgres 5432 2>/dev/null | tail -n 1 | sed -E 's/.*:([0-9]+)$/\1/'
)"
if [[ -z "${PUBLISHED_POSTGRES_PORT}" || "${PUBLISHED_POSTGRES_PORT}" == "0" ]]; then
  echo "Error: Postgres is running but the port is not published to the host."
  echo "A common cause is another Postgres container already using port ${DEFAULT_POSTGRES_PORT}."
  echo "Try stopping the conflicting container or set POSTGRES_PORT to a free port and rerun."
  exit 1
fi

POSTGRES_PORT="${PUBLISHED_POSTGRES_PORT}"

# Ensure the password matches the compose configuration, even if the volume was initialized
# with a different value. (The official postgres image doesn't re-apply POSTGRES_PASSWORD
# on subsequent runs when the data directory already exists.)
echo "Ensuring postgres credentials are aligned..."
ESCAPED_POSTGRES_PASSWORD="${POSTGRES_PASSWORD//\'/\'\'}"
$COMPOSE_CMD exec -T postgres psql -U postgres -d postgres -v ON_ERROR_STOP=1 -c \
  "ALTER USER postgres WITH PASSWORD '${ESCAPED_POSTGRES_PASSWORD}';" >/dev/null

# Keep the API's DATABASE_URL aligned with the chosen Postgres port (local-only override file).
API_ENV_LOCAL="apps/api/.env.local"
DATABASE_URL="postgresql://postgres:${POSTGRES_PASSWORD}@localhost:${POSTGRES_PORT}/isntgram"
cat > "${API_ENV_LOCAL}" <<EOF
# Auto-generated by scripts/dev-db.sh
# This file is ignored by git. Re-run pnpm run dev:db to refresh.
DATABASE_URL=${DATABASE_URL}
EOF

# Wait for MinIO to be ready
echo "Waiting for MinIO to be ready..."
until curl -f http://localhost:9000/minio/health/ready >/dev/null 2>&1; do
  echo "MinIO is not ready yet. Waiting..."
  sleep 2
done

echo "✅ Infrastructure is ready!"
echo "Postgres URL: ${DATABASE_URL}"
echo "MinIO URL: http://localhost:9000 (console: http://localhost:9001)"
echo "Bucket: isntgram-media"
echo ""
echo "To stop services, run: $COMPOSE_CMD down"
echo "To view logs, run: $COMPOSE_CMD logs postgres minio"
